### ISSUE TITLE
Some help with Google Sign in

### ISSUE THREAD

**Issue by aubm** [dgrijalva/jwt-go#116]
Hey !

I'm currently trying to use the library to parse and validate OIDC tokens issued from Google Sign-in. I used the README sample code as a starting point and tried to implement the "myLookupKey" function. 

So I fetch and parse the content of the Google discovery document (https://accounts.google.com/.well-known/openid-configuration), but I can't get my token validated.

I created a test repository here : https://github.com/aubm/golang-google-sign-in
I'm not sure what I need to return here https://github.com/aubm/golang-google-sign-in/blob/master/main.go#L49.

Thanks in advance :)

**Comment by aubm** [comment]
I have updated the code to return an *rsa.PublicKey in `myLookupKey `. Now I get the following error :  `crypto/rsa: verification error`. Any idea how to debug this ?

Here is the output of `fmt.Printf("%v", pk)` : `&{76994465367955004371129137084604598658361706301060610717088711974133306164776960529255861628681881117457914273308810939730572526182865978316317220965854297989559590880060248968305476904165830031749992810198020601186216798748334453081428471207636470873474565214307511500014517054883890205753591242095723537194461020379344464944250407358932186650078253893168514291100394980891807266051187622775103331683301184842917360945783993337575802134268760927301837774320922799478075954276877433086189535325996586123751555069556072028196130967478915730897764985403027311590904325894316126217060716308520015455271748731534711387 65537}`

**Comment by dgrijalva** [comment]
I'll try to have a look shortly.  Might take me a little bit.  Pretty busy day today.

**Comment by aubm** [comment]
No problem, thanks for the feedback :)

**Comment by dgrijalva** [comment]
That error is coming from crypto/rsa: "ErrVerification represents a failure to verify a signature. It is deliberately vague to avoid adaptive attacks."

It most likely means one of the following:
* the token you're passing is malformed/corrupted in some way.  This is unlikely since you got pretty far
* the key is not the correct key for the signature
* the key is malformed in some way

I think the third is the most likely.  I haven't spent much time with the JWK spec, so it's difficult to guess at specifics, but there are a lot of small details that matter.  Try using a JWK parsing library, such as the one linked below, and see if the problem goes away.

https://github.com/mendsley/gojwk

**Comment by aubm** [comment]
Hey :) it appears that there is an unhandled error in my code as this person pointed out http://stackoverflow.com/questions/35416762/google-signin-validation-error-using-jwt-go?noredirect=1#comment58639213_35416762.

Thank you for the link, I'll sure give it a try and let you know when I figure it out !

**Comment by dgrijalva** [comment]
Makes sense. I'm pretty sure they use JWK (a sibling of jwt) to encode that data. You can use an off the shelf library or follow the spec:

http://self-issued.info/docs/draft-ietf-jose-json-web-key.html

Good luck!

-dave

**Comment by aubm** [comment]
Hey ! I finally made it work fine. I ended up using the library you linked last week.

For the record : https://github.com/aubm/golang-google-sign-in/commit/703e198dfcdeace5b36bce8a3adb0b70622daef4

Thanks again for your time and your precious tips :)
