### ISSUE TITLE
jwt refreshing?

### ISSUE THREAD

**Issue by steviesama** [dgrijalva/jwt-go#156]
I'm spankin' new to jwt and I was wondering about refreshing tokens. I have a lot of thoughts on it, but they are just that. I've just been parsing the tokens that come in and if they parse to valid, I check the expiration date and decide whether to update the expiration field and call token.SignedString again. I'm not sure if this is what I should be doing.

I can't help but think about when is a good time to refresh the token. If I did it every login, that feels excessive. But waiting x amount of time makes me think of something where say you had the token set to a week and you refreshed it on like the 5th or 6th day after it being issued and the user not logging back on until the 8th day. That just feels strange.

Then again, I have zero idea about best practices for this sort of thing. I'd appreciate any feedback. I thought I read somewhere that tokens should refresh themselves, but I don't see where that is facilitated when I look at the source code.

Thanks

**Comment by dgrijalva** [comment]
This library is really only focused on the tokens themselves.  There are many different places in an application where JWTs can be useful.  It sounds like you're asking about OAuth best practices.  You may find better luck if you Google for OAuth access token refreshing.  That said, let me see if I can be helpful.

This is a pretty deep subject with lots of eccentricities, but here are some things you should think about:
* Who are the consumers of your tokens? Just internal?
* Is it acceptable to have shared state? Can you put something opaque like a session id in your token and store the rest of the details inside your service?
* What will you do if you need to quickly expire tokens that have been issued?
* What is the scope of what can be accessed with one of your tokens? What could happen if one fell into the wrong hands?

JWT makes it possible to have OAuth access tokens that do not require shared state.  You can put things like the user id into them and use an asymmetric signing method, allowing the tokens to be verified without any shared state or secrets.  The trade-off is, it's very difficult to expire tokens once issued.  If you do this, your tokens should be very short lived (think minutes).

On the flip side, if you have a centralized auth system that all requests will go through, you can afford to issue longer lived tokens, since you have a centralized place to store token invalidation information.  The trade-off is, this system becomes a bottleneck for your entire service as the application scales.

It's possible to use both of these, where you have a centralized service for issuing short lived access tokens from longer lived session tokens.  Which approach is best for your application depends on a lot of factors.

**Comment by steviesama** [comment]
I appreciate it. I'm writing a login/authentication microservice that has it's own page widget. So my other web apps have a central login. I'm mostly doing it as an exercise. I have a lot to think about regarding it. I think I envisioned a handful of ideas in what you had to say. I was thinking I was gonna have the centralized auth sometimes as it works with the idea of what I'm doing, but I was really hoping the token itself could act as a means of removing processing overhead from the server and having less DB space and processing taken up.

But I started to to think about blacklisting, and the user logging in from say another computer and obviously the issued token doesn't follow them. So if I wanted to have a persistent session, I'd have to put the expiration on it, and a tblUserSession or something with the last issued token, last-seen, etc. Where if the last seen til the current login is within the expiration time I can just refresh the token and shoot the new one back to the client, if outside of that time frame, then force a relog in.

I'm not sure if I'm thinking about this process in the correct way. I'm trying to think about logins across different endpoints.

**Comment by dgrijalva** [comment]
You might be overthinking the issue.  You'd have to have HUGE login volume for these refreshes to be very expensive.  I'd recommend starting at http://oauth.net, which outlines some best practices and is a good jumping off point for defining an auth service.

Here's the section of the OAuth 2 RFC that covers refreshing of tokens: https://tools.ietf.org/html/rfc6749#section-6
