### ISSUE TITLE
Breaking API changes

### ISSUE THREAD

**Issue by TheTincho** [dgrijalva/jwt-go#176]
Hi,

The release of v3 has introduced breaking API changes, which means that dependent project that are not vendoring in this library are instantly broken.

I wonder what is going to happen with these projects now: they might change their code to match this API, or maybe they will just keep a copy of the old version, possibly adding local patches to it. Are you going to maintain a v2 branch to fix bugs?

I know the go ecosystem has different and conflicting opinions on these issues, but as your downstream (I am one of the maintainers of go packages in Debian), it would be extremely helpful if you used some kind of SONAME change -for example gopkg.in- or other mechanism that avoids the mess that could result from this situation.

Thanks.

**Comment by dgrijalva** [comment]
Yeah.  This is an issue everyone has to contend with right now.  The official go team's position seems to be to recommend vendoring.  Go 1.7 even supports this by default.  This library uses semantic versioning to make it possible to use tools like gopkg.in, if you prefer.  We will continue to fix bugs on 2.x, but it will not receive new features.

**Comment by TheTincho** [comment]
Well, if you plan to keep fixing bugs for 2.x, then it would make sense for us to have a separate package for 3.x. Using gopkg.in or similar would make sense too, but I figure that is something you should control.

**Comment by dgrijalva** [comment]
This is a tricky issue. The Go team recommends vendoring dependencies.  Github doesn't provide a mechanism to proactively let watchers know of important changes.  The trouble with creating new packages with every major release is sort of the same.  People might not find it easily.

Another important consideration is that not all major changes are of the same scale.  3.0.0 had some pretty major API changes.  But, looking at tickets like #184, there are also going to be major releases that effect a minority of users.  Requiring a new package every time somewhat erodes the contract provided by [semver](semver.org), since, for small changes, it's tempting fudge the rules to make the release simpler.

**Comment by dgrijalva** [comment]
In general, dependency management for go is not a well solved problem today. I'd rather focus on improving this library and wait for all that to sort itself out before taking an explicit position.

**Comment by blainsmith** [comment]
FWIW most should be ensuring tests pass before pushing to production so even if a breaking change was to make it out it should be caught in most cases. Leveraging git tags and http://labix.org/gopkg.in you can get some sort of version protection.

If you doing Go development everyone is ware of the vendoring risks so pushing this project forward should be priority. Just my two cents. ;-)

BTW, I appreciate your work on this project!
