### ISSUE TITLE
Support pkcs8 from Apple APNs ?

### ISSUE THREAD

**Issue by laozi2** [dgrijalva/jwt-go#179]
Due to Apple APNs token authoration need jwt, and the privaite key is .p8, so how about add a function like this

<pre>
// Parse PEM encoded Elliptic Curve Private Key Structure
func ParsePKCS8PrivateKeyFromPEM(key []byte) (*ecdsa.PrivateKey, error) {
    	var err error

	    // Parse PEM block
    	var block *pem.Block
	    if block, _ = pem.Decode(key); block == nil {
	         	return nil, ErrKeyMustBePEMEncoded
	    }

	    // Parse the key
	    var parsedKey interface{}
	    if parsedKey, err = x509.ParsePKCS8PrivateKey(block.Bytes); err != nil {
		         return nil, err
	    }

	     var pkey *ecdsa.PrivateKey
	    var ok bool
	    if pkey, ok = parsedKey.(*ecdsa.PrivateKey); !ok {
		    return nil, ErrNotECPrivateKey
	}

	return pkey, nil
}

</pre>

**Comment by dgrijalva** [comment]
Is PKCS6 encoding common for elliptic curve keys?  I didn't include decoders for those keys because I couldn't find consensus around popular encoding schemes.

The RSA ones are there as a historic artifact.  We used to do that automatically, but that turned out to be not a great idea.  Rather than totally remove that feature, I just included it as a helper.  It seems like it should be out of scope for this library to include helpers for every encoding technique for every type of key.

What do you think?

**Comment by laozi2** [comment]
As I know,  the Apple APNs service need PKCS8  encoding for ES256 to generate jwt string.   and maybe    you are right, it's not necessary to support every type of key.
