### ISSUE TITLE
StandardClaims Audience must be an array of strings according to https://tools.ietf.org/html/rfc7519#section-4.1

### ISSUE THREAD

**Issue by pakalvoltan** [dgrijalva/jwt-go#184]
According to https://tools.ietf.org/html/rfc7519#section-4.1 the aud claim in StandardClaims should be an array of strings and currently in jwt-go is defined as string.

**Comment by dgrijalva** [comment]
Yep.  That's definitely a thing.  It's a backwards incompatible change, sadly.

**Comment by blainsmith** [comment]
Actually that says it can be either a string or an array to make things worse ;-)

**Comment by kekoav** [comment]
@dgrijalva I submitted a PR to fix Validation of Audience, I don't think this is a backwards incompatible change since I'm only supporting validation with `MapClaims`. I've left `StandardClaims` alone as changing that would be backwards incompatible. Let me know what you think. Tests included. At least this makes audience usable in the way the RFC states- not having support in `StandardClaims` is a minor annoyance. The inability to validate Audience from a JWT at all if it is an array is kind of a big deal.

**Comment by dgrijalva** [comment]
Thanks.  I'm looking at it.  This is a real weakness of the built-in JSON decoder.  Basically all the gymnastics we've done in this library were to work around its limitations.

**Comment by gaillard** [comment]
This impacts us too so any traction here would be appreciated :)

**Comment by dgrijalva** [comment]
Does anyone have any good ideas for how to fix this?  The spec allows for audience to be a string or array of strings.  That's doesn't align well with the go json stuff.  Here are the options I can think of:

* fork standard claims to have two versions (this will probably get messy fast)
* change `aud` to be `interface{}` and handle it that way
* change `aud` to be `[]string` and build in processing to turn a single string into a single entry slice
* drop `aud` from `StandardClaims`
* drop `aud` from `StandardClaims` and add some wrapper types that add specific `aud` implementations

**Comment by blainsmith** [comment]
I've always felt that spec was too relaxed when it comes to defining a proper data contract. Even in JS checking for the array instance is silly. I would argue that you can take the high road and use `[]string` since you can always have a single element in there. At least this gives the best option for flexibility when using JWTs.

**Comment by kekoav** [comment]
I agree with @blainsmith on using a `[]string` since it can encode both representations, and simplifies usage greatly.

What about introducing a new more generic `Claims` object that covers all the needs of the spec(and maybe even more such as extra non-standard claims) in a clean interface that is easy to use/manipulate? Dragging around imperfect abstractions will just be a burden. This improved claims object could provide a balance between `StandardClaims` and `MapClaims` but also enforce spec compliance(which is a major weakness of `MapClaims`) and ensure serialization/deserialization does the sane thing. Any interest in such an attempt?

**Comment by dgrijalva** [comment]
I'll happily review such a pr. 

-dave

**Comment by nathany** [comment]
👍 for "change aud to be []string and build in processing to turn a single string into a single entry slice"

**Comment by nathany** [comment]
Though #188 only helps for MapClaims.

StandardClaims or a new Claims type doesn't seem to be addressed yet?

**Comment by chrisbbe** [comment]
What about https://github.com/dgrijalva/jwt-go/pull/286 ?

**Comment by dgrijalva** [comment]
This is landed in v4 branch
