### ISSUE TITLE
Verifying signature of decoded JWT

### ISSUE THREAD

**Issue by mrichman** [dgrijalva/jwt-go#222]
I'm using AWS Cognito user pools to attempt to authenticate users.

These are their steps to verify the access token:

> To verify a signature for access tokens:

		1. Download and store the JSON Web Token (JWT) Set for your user pool.

			You can locate them at https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json.
			Each JWT should be stored against its kid. Please note this is a one time step before your web APIs can process the tokens.
			Now you can perform the following steps each time the access token is used against your web APIs.

		2. Decode the token string into JWT format.

		3. Check the iss claim. It should match your user pool.

			For example, a user pool created in the us-east-1 region will have an iss value of https://cognito-idp.us-east-1.amazonaws.com/{userPoolId}.

		4. Check the token_use claim.

			If you are only accepting the access token in your web APIs, its value must be access.

		5. Get the kid from the JWT token header and retrieve the corresponding JSON Web Key that was stored in step 1.

		6. Verify the signature of the decoded JWT token.

		7. Check the exp claim and make sure the token is not expired.

		    You can now trust the claims inside the token and use it as it fits your requirements.

I have the following code to parse a the JWT access token returned by Cognito and then attempt to validate/verify it against my JWKS:

```
jwtToken := aws.StringValue(resp.AuthenticationResult.AccessToken)

token, err := jwt.Parse(jwtToken, getKey)
if err != nil {
	panic(err)
}

if claims, ok := token.Claims.(jwt.MapClaims); ok && token.Valid {
	fmt.Println(claims["username"])
	if claims["token_use"] != "access" {
		log.Fatal("token_use mismatch", claims["token_use"])
	}
} else {
	fmt.Println(err)
}

func loadKeySet() error {
	var err error
	keySet, err = jwk.FetchHTTP(jwksURL + "/" + userPoolID + "/.well-known/jwks.json")
	if err != nil {
		return err
	}
	return nil
}

func getKey(token *jwt.Token) (interface{}, error) {
	keyID, ok := token.Header["kid"].(string)
	if !ok {
		return nil, errors.New("expecting JWT header to have string kid")
	}

	if key := keySet.LookupKeyID(keyID); len(key) == 1 {
		return key[0].Materialize()
	}

	return nil, errors.New("unable to find key")
}

```

My question is, is the above sufficient to satisfy step 6 "Verify the signature of the decoded JWT token"? In other words, is `jwt.Parse()` and `token.Valid` enough to verify the signature, or do I need to do more?

Thanks!

**Comment by dgrijalva** [comment]
The primary function of `Parse` (beyond just parsing) is to ensure that the _signature_ is valid.  It will also call the `Valid` on the claims object.  If you use one of the built in claims types, it will automatically also validate standard claims such as `exp`.

For any behavior beyond what's defined in the standard, you should handle those yourself either post-parse or by implementing your own claims type.  In your example, `token_use` is outside the scope of this library, so that validation would be your responsibility.

One thing I would recommend is that you make sure the signing method matches your expectation.  Recent versions of this library rely on the type system to prevent an attacker from triggering the wrong signature validation logic, but it's still worth actually checking.
