### ISSUE TITLE
JWT Parse Error

### ISSUE THREAD

**Issue by AbooJan** [dgrijalva/jwt-go#224]
Golang: `1.8.2`
jwt-go:  `latest version`

---

I make a jwt like this:
```
	createAt := time.Now().Unix()
	expireAt := time.Now().AddDate(0,0,10).Unix()
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
		"usr_id": usr.Id,
		"c_at": createAt,
		"e_at": expireAt,
	})
	tokenStr,err := token.SignedString([]byte(jwtKey))
```
the param `usr.Id` type is `int64`.

---

But when I parse the jwt like this:
```
	token, err := jwt.Parse(tokenStr, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("Unexpected signing method: %v", token.Header["alg"])
		}
		return []byte(jwtKey), nil
	})

	if claims, ok := token.Claims.(jwt.MapClaims); ok && token.Valid {
		uid := claims["usr_id"].(int64)
		expTS := claims["e_at"].(float64)
        }
```
It get panic at the type assertion: `type interface{} is float64, not int64`

I don't know Why?🤔

I had set the value for key `usr_id` and `e_at` is `int64` type, but why it change to `float64` ?

Some one can help me,
Thanks~ 
🍭

**Comment by dgrijalva** [comment]
This is a side effect of how the underlying JSON parser works.  The JSON spec doesn't specify an integer format.  All numbers are parsed, by default as `float64`.  There are two ways to alter this behavior:
- use the JSONNumber flag, which uses the [`json.Number`](http://godoc.org/encoding/json#Number) type instead of `float64`
- use a [custom struct type](https://github.com/dgrijalva/jwt-go/blob/master/example_test.go#L56) to parse your token
