### ISSUE TITLE
Support verifying keys that were issued in the "near" future.

### ISSUE THREAD

**Issue by joeblubaugh** [dgrijalva/jwt-go#226]
I've seen issues verifying JWTs issued by credible orgs (like Google) when there is clock skew between my system and Google's network. I'd like to propose a feature where we permit some amount of tolerance around verifying issued-at times on JWTs to handle these clock skew issues.

I'm happy to send a PR myself too, but I wanted to see if there was support for doing that work first.

**Comment by joeblubaugh** [comment]
Hello,

Any thoughts on this? I've noticed a number of other JWT libraries support features like this to help accomodate mild clock skew in systems.

**Comment by dgrijalva** [comment]
I believe some work was done around leeway a while back. If I recall, it hasn't landed because it wasn't API compatible. I try to bundle up API breaking changes into major releases to avoid messing up people's environments. I'd be happy to land something that didn't break the API, or maybe it's time to review breaking changes and work towards the next major version.

There are methods for working around this today, though admittedly clumsy, by wrapping the claims type and overriding the validation behavior in question.

This request has come frequently enough that it deserves a good solution.

**Comment by baconstrudel** [comment]
Shouldn't the fact that a claim was issued "in the future" be ignored as long as the clock of the validator is ahead of the nbf (if there is an nbf claim)?

**Comment by darkk** [comment]
I'd add my two cents to leeway/backward-compatibility discussion:
- the resolution of `iat`, `nbf` and `exp` is 1 second
- ±10ms clock difference still can be an issue in low RTT environment (e.g. intra-datacenter) if the token is issued by box A at 00:01.000s and ~immediately (e.g. within 1ms) presented to a box B that has wall clock 00:00.991s, so 10ms clock difference + 1ms RTT can easily lead to 1s "error" due to rounding. I take 10ms in this example, as it's _usual_ (non-pathological) clock difference across VMs of our small Geo-distributed NTP-synced cluster
- there is "[leap second](https://en.wikipedia.org/wiki/Leap_second)" and "leap smearing", so it's perfectly legal for wall-clocks to be ~1s away in distributed environment once in a while depending on the implementation of leap second handling on different boxes

I'd suggest to add default leeway of at least 3s for `nbf` and `iat` (`iat` due to #246) to _existing_ validation API. Maybe 5s to make it round. I think, it may be considered a backward-compatible change that fixes an issue of token being invalid in distributed environment right after creation due to small clock skew.

I've observed small `gettimeofday()` steps backward on ordinary multicore Linux machine in 2011 without NTP, so "distributed" may be read as "multi-CPU" at least in some cases :-)

Sidenote on magic values: go-jose from Square is even more permissive regarding leeway, it's [1 minute](https://github.com/square/go-jose/blob/v2/jwt/validation.go#L22) and [it's default](https://github.com/square/go-jose/blob/v2/jwt/validation.go#L48-L52).

**Comment by dgrijalva** [comment]
@darkk a default, small leeway value is an interesting idea. Thanks.

In v4, we're dropping the in-built IAT validation. The spec says this value is intended to be informational rather than verified.

We are also adding support for user defined leeway. I'm going to think about a default value in addition.

**Comment by adamgering** [comment]
Can we get this in 3.2? When either 3.2 or 4.0?

**Comment by dgrijalva** [comment]
leeway support has landed in 4.0 branch
