### ISSUE TITLE
Verify claims before verifying signature

### ISSUE THREAD

**Issue by michele** [dgrijalva/jwt-go#228]
I was wondering if it wouldn't make sense to verify a token's claims before calling keyFunc to verify the signature.

The reasoning, at least in our use case, is that we need to retrieve the secret from a DB, so while we could easily cache it in memory and keep it around, I don't think it makes sense to hit the DB if the claims are not valid anyways.

If it's something that makes sense, I'd be willing to write a PR for it.

**Comment by sagikazarmark** [comment]
I don't really think that's a good way to go. First thing I can think of is if verifying the signature is not the first thing then it's much easier to forget verifying it at all or at least makes the whole thing much more error prone.

Also verifying token claims can also involve DB reads in some cases, there would be no gain there.

You already mentioned a much better solution (keep the secret in memory), I would go with that one.

**Comment by dgrijalva** [comment]
This may be an over-optimization. There's not a lot of overlap between use cases. Signature verification should only ever fail if the token is forged or if the key has been removed from use. Claims validation should only fail if a valid token has expired or is being misused. 

The paranoid non-security-expert in me says you shouldn't do anything with claims until you're sure the signature is valid. If you had a really high rate of expired tokens being used, you could make an argument for doing otherwise. In that case, it could be worth doing some early validation. I think this is likely a corner case that could be worked around with current tools.

The token has already been parsed when keyfunc is called. You could add a preemptive check before you lookup your key in there. The built in check will also run after signature validation, but the cost of that should be acceptable.

**Comment by dgrijalva** [comment]
I'm not really sure what the right thing to do here is. Reversing the processing order makes me nervous, but not for any obviously good reason.

**Comment by michele** [comment]
Reading your comments, I have admit I tend to agree with you, especially with @dgrijalva saying this would be an over-optimization. I'd say 90% of the calls we get are with long lasting tokens and only 10% or less are with tokens expiring in less than 24 hours. So, barring anyone heavily sending forged tokens, we'd be optimizing for a small subset of requests.

On top of this, we have a microservice validating the tokens and it is very rarely restarted, so in-memory cache should be good enough, well, actually it is good enough as it has been running in production for the past month.

I think we can close this one. Thanks for your comments!

**Comment by sagikazarmark** [comment]
@michele out of curiosity: why do you have a separate (nano?)service for validating JWT tokens?

Doesn't that kinda defeat the whole purpose of having a stateless "session"? (I mean there is zero gain from not checking the token validity with a third component, because you actually do) I guess there is more context which you haven't explained in detail, but I'm curious about the use case (if it's something you can share).
