### ISSUE TITLE
ParseFromRequest is not found 

### ISSUE THREAD

**Issue by datavisorfrankhe** [dgrijalva/jwt-go#279]
Hello, I am following Web Development with Go book to learn Go.
For jwt token, it mentioned we can use this to obtain the toke:

```
token, err := jwt.ParseFromRequest(r, func(token *jwt.Token) (interface{}, error) {
// since we only use one private key to sign the tokens,
// we also only use its public counter part to verify
return verifyKey, nil
})
```

But I don't see ParseFromRequest method, is this already removed?

Thanks

**Comment by dgrijalva** [comment]
`ParseFromRequest` has been moved to the `request` subpackage in the latest
version. Breaking changes like this only occur in major version releases
and are always documented in the VERSION_HISTORY. Thanks!

**Comment by datavisorfrankhe** [comment]
Thanks for your confirmation! 
I am checking ParseFromRequest in request, can you please tell me if I want to use:

token, err := request.ParseFromRequest(r, func(token *jwt.Token) (interface{}, error) {
		// since we only use one private key to sign the tokens,
		// we also only use its public counter part to verify
		return verifyKey, nil
	});

what will be accurate format? 

I am very new to go, so please forgive my ignorance here

Thanks

**Comment by dgrijalva** [comment]
See the documentation here: https://godoc.org/github.com/dgrijalva/jwt-go/request#ParseFromRequest

`ParseFromRequest` take three arguments:
* The request
* An extractor
* The token lookup function

The extractor's job is to extract the token string from the request. There are a bunch of built in extractors or you can define your own. There is no single 'correct' solution since different services use tokens in different ways. One of the more common approaches is handled using the `OAuth2Extractor`.
