### ISSUE TITLE
Violating of Liskovs substitution principle

### ISSUE THREAD

**Issue by rkl-** [dgrijalva/jwt-go#329]
In my opinion, the method `func (t *Token) SignedString(key interface{}) (string, error)` in `token.go`, violates the Liskovs substitution principle. `key` is expected to be of type `interface{}` but on a deeper layer it has to be of type `[]byte`. This violates the substitution principle, because `SignedString` has an unexpected behaviour. The method  claims to handle `interface{}` keys, but that's not true.

**Comment by dgrijalva** [comment]
I don't disagree. It's a compromise. It's also the most common place users get tripped up by this library.

The challenge is, every signing method takes a different key type. Even uniform interfaces like `crypto.Signer` aren't really sufficient. We're adding support for `crypto.Signer` in v4 and it still has to do a type check to ensure the signer will use the appropriate algo.

I considered putting the `SignedString` method on the `SigningMethod` interface instead of the `Token`, but it doesn't solve the issue. Go doesn't provide a way to define an interface where every implementation has different types in its signature.

There are many places in the standard library where they rely on documentation (and error messages) to define what is and is not a valid input. The `encoding/json` package, upon which this library is based, is a good example.

All that said, if you have a suggestion for a better API, I'm all ears.

**Comment by rkl-** [comment]
Is it necessary, to define the signing method before the used key?

**Comment by dgrijalva** [comment]
When creating a token, you must specify the signing method as an input to the `New` function.

When parsing, the signing method is inferred from the `alg` property in the token's header. This is one of the reasons the key is provided by a callback instead of inline. Before the callback is invoked, the header is parsed and the `Method` property is populated with the correct signing method.

**Comment by dgrijalva** [comment]
Looks like this is resolved. Please feel free to reopen if you feel otherwise.
