### ISSUE TITLE
Security Vulnerability: failed type assertion leads to bypassing Audience verification

### ISSUE THREAD

**Issue by christopher-wong** [dgrijalva/jwt-go#422]
if `m["aud"]` happens to be `[]string{}`, as allowed by the spec, the type assertion fails and the value of `aud` is `""`. This can cause audience verification to succeed even if the audiences being passed are incorrect if `required` is set to `false`.

https://github.com/dgrijalva/jwt-go/blob/master/map_claims.go#L16
```go
// Compares the aud claim against cmp.
// If required is false, this method will return true if the value matches or is unset
func (m MapClaims) VerifyAudience(cmp string, req bool) bool {
	aud, _ := m["aud"].(string)
	return verifyAud(aud, cmp, req)
}
```

https://play.golang.org/p/Pnvvqfehl9K

**Comment by alexellis** [comment]
FYI the snippet has expired on the playground.

**Comment by melkikh** [comment]
> FYI the snippet has expired on the playground.

The original one: https://play.golang.org/p/Pnvvqfehl9K
(K was missed in URL)

**Comment by ksegun** [comment]
It looks like this is addressed in v4, which uses go modules, proposed changes seem identical

`go get github.com/dgrijalva/jwt-go/v4`

**Comment by brianmay** [comment]
I believe #286 will fix this for older versions.

**Comment by faraonc** [comment]
> It looks like this is addressed in v4, which uses go modules, proposed changes seem identical
> 
> `go get github.com/dgrijalva/jwt-go/v4`

I am not sure if using V4 is sufficient. The library seems to be abandoned. It might be be better to use another JWT compliant from https://jwt.io/

**Comment by aldas** [comment]
So this is problem when:
* JWT tokens are created `aud` containing multiple urls (`[]string` instead of `string`)
   * those tokens are *probably* created externally as [jwt.StandardClaims](https://github.com/dgrijalva/jwt-go/blob/dc14462fd58732591c7fa58cc8496d6824316a82/claims.go#L19) assumes `Audience` to be `string` not `[]string`
   * as token is **still** verified agains signing key this would mean that token **needs** to be originated from authoritative source (key)
* Library user explicitly checks (codes thoses check by their own) claims with `.VerifyAudience(cmp string, req bool) bool`
* `aud` is check set to **optional** (by application developer) by `.VerifyAudience("https://mysite.com", false)` call  thus making 
  ```go
	if aud == "" {
		return !required
	}
  ```
  return wrongly true and not checking if `aud` actually matches to token audiences values

I would say it is a problem when you are **reusing** token signing keys for multiple sites/applications (even for sites that you are not meaning to use - by aud values) or attacker has compromised your key and uses it on rogue application/site and has coded its stuff to check aud - which is game over anyway.

So easiest workaround till fix is - make sure that you are not reusing signing keys (for applications that have different audience `aud`)
