### ISSUE TITLE
Invalidating tokens

### ISSUE THREAD

**Issue by Tagnard** [dgrijalva/jwt-go#63]
Is there an easy way to invalidate tokens from the server side?

**Comment by dgrijalva** [comment]
This is really up to your application.  Once you hand out a token, it can't be modified (by design).  

If you have a unique identifier in each token you issue, you can keep an invalidation list.  

Another option is to put an issued at date in the token.  Then you can reject all tokens issued before a certain point.

Yet another option is to make tokens short lived and provide a refresh mechanism.  So you can just not re-issue a token you want invalidated.

You'll probably want some combination of the above.  Maybe with some others?  There are a lot of factors to consider, not limited to: app architecture, scale, security concerns, and complexity.
